In [1]:
# Recursion
def func_a(a):
    print("In function A",a)
    if a>6:
        func_b(a-1)
    
def func_b(b):
    print("In function B:",b)
    if b>6:
        func_a(b-1)
    
func_b(10)

In function B: 10
In function A 9
In function B: 8
In function A 7
In function B: 6


In [5]:
# Fixed-Sized Stack

import numpy as np
array = np.zeros(10)
top = 0

def push(top,element):
    if top==array.shape[0]-1:
        print("Stack Overflow!!! Cannot push element into Stack...")
    else:
        top = top+1
        array[top]=element
    display(top)
    return top

def pop(top):
    if top<0:
        print("Stack Underflow!!! Cannot pop element from Stack...")
    else:
        top = top-1
    display(top)
    return top

def display(top):
    print("Stack display:",array[0:top+1])  
        
def stack():
    top = -1 
    choice = 1
    while choice > 0:
        choice = input("Select operation:\n1:Push\n2:Pop\n3:Quit\nChoice=")
        choice = int(choice)
        if choice==0 or choice>2:
            print("You chose to break!!!")
            break
        elif choice==1:
            e = input("Element=")
            top = push(top,int(e))
        else:
            top = pop(top)     

In [6]:
stack()

Select operation:
1:Push
2:Pop
3:Quit
Choice=2
Stack Underflow!!! Cannot pop element from Stack...
Stack display: []
Select operation:
1:Push
2:Pop
3:Quit
Choice=1
Element=11
Stack display: [11.]
Select operation:
1:Push
2:Pop
3:Quit
Choice=1
Element=12
Stack display: [11. 12.]
Select operation:
1:Push
2:Pop
3:Quit
Choice=1
Element=13
Stack display: [11. 12. 13.]
Select operation:
1:Push
2:Pop
3:Quit
Choice=2
Stack display: [11. 12.]
Select operation:
1:Push
2:Pop
3:Quit
Choice=2
Stack display: [11.]
Select operation:
1:Push
2:Pop
3:Quit
Choice=2
Stack display: []
Select operation:
1:Push
2:Pop
3:Quit
Choice=2
Stack Underflow!!! Cannot pop element from Stack...
Stack display: []
Select operation:
1:Push
2:Pop
3:Quit
Choice=4
You chose to break!!!


In [2]:
# Fixed Size - Circular queue
import numpy as np
array=np.zeros(5)-1


def push(element,front,rear): # -------------------------------------------  
    if check_push(front,rear)==1:
        rear=rear+1
        if rear==array.shape[0]:
            rear=0
        array[rear]=element        
        if front<0:
            front=rear
    else:
        print("Queue Overflow !!!")
    return front,rear

def check_push(front,rear):    
    if (front==0 and rear+1==array.shape[0]) or (rear+1)==front:
        return 0
    else:
        return 1    
        
def pop(front,rear): # ---------------------------------------------------
    if check_pop(front,rear)==1:
        if front==rear:
            front=-1
            rear=-1
        else:
            front=front+1
            if front==array.shape[0]:
                front=0
    else:
        print("Queue Underflow !!!")
    return front,rear

def check_pop(front,rear):
    if (front>=0 and front<=rear and rear-front>=0) or (rear<front):
        return 1 
    else:
        return 0
    
def queue():    
    choice = 1
    front=-1
    rear=-1
    while choice > 0:
        choice = input("Select operation:\n1:Push\n2:Pop\n3:Quit\nChoice=")
        choice = int(choice)
        if choice==0 or choice>2:
            print("You chose to break!!!")
            break
        elif choice==1:
            e = input("Element=")
            front,rear = push(int(e),front,rear)            
            print(array)
        else:
            front,rear = pop(front,rear)             
            print(array)
    

In [5]:
queue()

Select operation:
1:Push
2:Pop
3:Quit
Choice=1
Element=1
Push= [0, 0]
[ 1. -1. -1. -1. -1.]
Select operation:
1:Push
2:Pop
3:Quit
Choice=1
Element=2
Push= [0, 1]
[ 1.  2. -1. -1. -1.]
Select operation:
1:Push
2:Pop
3:Quit
Choice=1
Element=3
Push= [0, 2]
[ 1.  2.  3. -1. -1.]
Select operation:
1:Push
2:Pop
3:Quit
Choice=1
Element=4
Push= [0, 3]
[ 1.  2.  3.  4. -1.]
Select operation:
1:Push
2:Pop
3:Quit
Choice=1
Element=5
Push= [0, 4]
[1. 2. 3. 4. 5.]
Select operation:
1:Push
2:Pop
3:Quit
Choice=1
Element=6
Queue Overflow !!!
Push= [0, 4]
[1. 2. 3. 4. 5.]
Select operation:
1:Push
2:Pop
3:Quit
Choice=2
Pop= [1, 4]
[1. 2. 3. 4. 5.]
Select operation:
1:Push
2:Pop
3:Quit
Choice=2
Pop= [2, 4]
[1. 2. 3. 4. 5.]
Select operation:
1:Push
2:Pop
3:Quit
Choice=1
Element=6
Push= [2, 0]
[6. 2. 3. 4. 5.]
Select operation:
1:Push
2:Pop
3:Quit
Choice=1
Element=7
Push= [2, 1]
[6. 7. 3. 4. 5.]
Select operation:
1:Push
2:Pop
3:Quit
Choice=1
Element=34
Queue Overflow !!!
Push= [2, 1]
[6. 7. 3. 4. 5.]
Select

In [12]:
# Bubble Sort
n=5
r=np.random.random(n)*10
print("Original Array=",r)
for i in range(n):
    for j in range(n):
        if r[i]>r[j] and i<j:
            t=r[i]
            r[i]=r[j]
            r[j]=t
print("Sorted Array=",r)                            

Original Array= [9.3990505  3.97416478 2.8037671  5.6488926  9.93647441]
Sorted Array= [2.8037671  3.97416478 5.6488926  9.3990505  9.93647441]


In [14]:
# Selection Sort
n=5
a=np.random.random(n)*10
print("Original Array=",a)
for i in range(n):    
    j_index = i
    for j in range(n):
        if a[j_index] > a[j] and i<j:          
            j_index = j            
    t=a[i]
    a[i]=a[j_index]
    a[j_index]=t    
print("Sorted Array=",a)             

Original Array= [3.92249241 0.59717895 3.66496157 8.28772664 0.30863543]
Sorted Array= [0.30863543 0.59717895 3.66496157 3.92249241 8.28772664]


In [17]:
# Linear Search
b=np.array([4,3,7,5,73,34,45])
search=34
for i in range(b.shape[0]):
    if b[i]==search:
        print("Element present in position:",i)
        

Element present in position: 5


In [22]:
# Binary Search
b=np.array([4,3,7,5,73,34,45])
n=b.shape[0]
search=34

b=np.sort(b)
print("Original Array=",b)

mid=int(n/2)
stop = 0
while stop==0:    
    if b[mid]==search:
        print("Element present in position:",mid)
        stop=1
    else:
        if search<=b[mid]:      
            mid = int(0+mid/2)
        else:                   
            mid = int((mid+n)/2)

Original Array= [ 3  4  5  7 34 45 73]
Element present in position: 4
